database:
  connstring: host=localhost port=5432 dbname=webapp user=postgres password=postgres sslmode=disable
auth:
  provider:
    google:
      client_id: 212763908463-e0tpnd2jjaqusrj3svfgcp1m792etivb.apps.googleusercontent.com
      client_secret: SOIHmffrwyTqN0QzDfIuaJqq
    github:
      client_id: 0f08295be2677845e936
      client_secret: b313ce977b07a6e25f778caa8ef8b286a03f2924
  state_expiry: 2 # minutes
  access_token:
    secret: secret-access-token-123
    expiry: 15 # minutes
  refresh_token:
    secret: secret-refresh-token-213
    expiry: 10080 # minutes
  cache:
    db: 1
    redis:
      host:
      port: 6379
      password: